include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    always_specify_types: false
    avoid_print: true
    omit_local_variable_types: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    unnecessary_late: true
    use_super_parameters: true
